### ISSUE TITLE
Another option

### ISSUE THREAD

**Issue by ghost** [h9nt/IGStuff#1]
Instead of reversing the client-side encryption, you can use an & symbol to bypass completely. Works on both Facebook and Instagram, password is plaintext password.

```js
var password = "supersecretpassword";

var body = {
    encpass: `#PWD_BROWSER:0:&:${password}`
}
```

**Comment by h9nt** [comment]
> Instead of reversing the client-side encryption, you can use an & symbol to bypass completely. Works on both Facebook and Instagram, password is plaintext password.
> 
> ```js
> var password = "supersecretpassword";
> 
> var body = {
>     encpass: `#PWD_BROWSER:0:&:${password}`
> }
> ```

thank u for this option, i will notice it for the next time!

**Comment by h9nt** [comment]
> Instead of reversing the client-side encryption, you can use an & symbol to bypass completely. Works on both Facebook and Instagram, password is plaintext password.
> 
> ```js
> var password = "supersecretpassword";
> 
> var body = {
>     encpass: `#PWD_BROWSER:0:&:${password}`
> }
> ```

u know if its work for web? or both like web/mobile?

**Comment by ghost** [comment]
> > Instead of reversing the client-side encryption, you can use an & symbol to bypass completely. Works on both Facebook and Instagram, password is plaintext password.
> > ```js
> > var password = "supersecretpassword";
> > 
> > var body = {
> >     encpass: `#PWD_BROWSER:0:&:${password}`
> > }
> > ```
> 
> u know if its work for web? or both like web/mobile?

I've completely reversed all of Meta's private API's, both browser and mobile versions as well. I can help you out with anything you need if you message me on Telegram @Hartman50, but here is my repo on the login request. (For Facebook, but it's very, very similar to Instagram and Threads.)

[My Github Repo](https://github.com/Hartman5/Facebook-Login-Request-Reversed)

**Comment by h9nt** [comment]
> > > Instead of reversing the client-side encryption, you can use an & symbol to bypass completely. Works on both Facebook and Instagram, password is plaintext password.
> > > ```js
> > > var password = "supersecretpassword";
> > > 
> > > var body = {
> > >     encpass: `#PWD_BROWSER:0:&:${password}`
> > > }
> > > ```
> > 
> > 
> > u know if its work for web? or both like web/mobile?
> 
> I've completely reversed all of Meta's private API's, both browser and mobile versions as well. I can help you out with anything you need if you message me on Telegram @Hartman50, but here is my repo on the login request. (For Facebook, but it's very, very similar to Instagram and Threads.)
> 
> [My Github Repo](https://github.com/Hartman5/Facebook-Login-Request-Reversed)

sure thank u! i will contact u
